IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/v0.1.5
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc-lfe-gem
PROJECT_PATH := ../../plc-lfe-gem/plc-lfe-gem.tsproj
PLC = plc_lfe_gem

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
